---
generic-service:
  nameOverride: hmpps-probation-estate-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-probation-estate-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-probation-estate-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SPRING_R2DBC_PROPERTIES_SSL: true
    SPRING_R2DBC_PROPERTIES_SSL_ROOT_CERT: "/home/appuser/.postgresql/root.crt"

  livenessProbe:
    httpGet:
      path: /health
  readinessProbe:
    httpGet:
      path: /health
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-probation-estate-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_address"
      DATABASE_NAME: "database_name"
  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-probation-estate-api
  alertSeverity: hmpps-tier