generic-service:
  nameOverride: hmpps-probation-estate-api

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-probation-estate-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-probation-estate-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius.hmpps.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  livenessProbe:
    httpGet:
      path: /health
  readinessProbe:
    httpGet:
      path: /health
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-probation-estate-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "AUTH_API_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "AUTH_API_CLIENT_SECRET"
  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-probation-estate-api
  alertSeverity: hmpps-tier
