---

generic-service:
  ingress:
    host: hmpps-probation-estate-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  scheduledDowntime:
    enabled: true

# Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
generic-prometheus-alerts:
  businessHoursOnly: true