---

generic-service:
  ingress:
    host: hmpps-probation-estate-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  scheduledDowntime:
    enabled: true