INSERT INTO team (code, name, ldu_code) VALUES ('N52MAG', 'Multi-Agency Gang Unit (MAGU)', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52AL2', 'BCCF Pending Allocations Central', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52AL4', 'BCCF Pending Allocations East', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52AL3', 'BCCF Pending Allocations North', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52AL1', 'BCCF Pending Allocations South', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52BlO', 'Birmingham Integrated Offender Management', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52BlS', 'Birmingham Integrated Offender Management', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52YAC', 'Young Adults Central Birmingham', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52YAE', 'Young Adults East Birmingham', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52YAN', 'Young Adults North Birmingham', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52YAS', 'Young Adults South Birmingham', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52SAS', 'IOM Staffordshire', 'N52BIRL');
INSERT INTO team (code, name, ldu_code) VALUES ('N52SAM', 'Walsall and Wolverhampton Womens Team ', 'N52BIRL');
