INSERT INTO team (code, name, ldu_code) VALUES ('N55BR4', 'Barnsley Sentence Management Team 4', 'N55BARL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55BCR', 'Bradford and Calderdale Responsive Management Hub', 'N55NBC' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55B11', 'Bradford Sentence Management Team 11', 'N55BRAL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55B12', 'Bradford Sentence Management Team 12', 'N55BRAL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55CM4', 'Calderdale Sentence Management Team 4', 'N55CAL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55DM6', 'Doncaster Sentence Management Team 6', 'N55DONL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55DRH', 'Doncaster Responsive Management Hub', 'N55DONL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55HRH', 'Hull and East Riding Responsive Management Hub', 'N55NHEY' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55H11', 'Hull Sentence Management Team 11', 'N55HUL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55H12', 'Hull Sentence Management Team 12', 'N55HUL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55H13', 'Hull Sentence Management Team 13', 'N55HUL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55KRH', 'Kirklees Responsive Management Hub', 'N55KIRL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55LS8', 'Leeds IOM (LSM8)', 'N55LEEL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55LRM', 'Leeds Responsive Management Hub', 'N55LEEL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55NRH', 'North and North East Lincs Responsive Management Hub', 'N55NNEL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55NEI', 'North East Lincolnshire IOM Team', 'N55NELL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55NLM', 'North Lincolnshire IOM Team', 'N55NOL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55YNR', 'North Yorkshire Responsive Management Hub', 'N55NYNY' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55SIM', 'Sheffield Integrated Management Team', 'N55SHEL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55SRH', 'Sheffield Responsive Management Hub', 'N55SHEL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55WS6', 'Wakefield Sentence Management Team 6', 'N55WAKL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55WRH', 'Wakefield Responsive Management Hub', 'N55WAKL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55YRM', 'York Responsive Management Hub', 'N55YORL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55RS4', 'Rotherham Sentence Management Team 4', 'N55ROTL' );
INSERT INTO team (code, name, ldu_code) VALUES ('N55RBR', 'Barnsley and Rotherham Responsive Management Hub', 'N55ROTL' );
